Output form_with_button.txt
Output form_with_button.gif
Set Width 1800
Set Height 800
Set FontFamily "Ubuntu Mono"
Set FontSize 20
Set Padding 0
Set Margin 0
Set Shell bash
Hide
Type "./pam_authd socket=/tmp/authd.sock"
Enter
Sleep 100ms
Show

Hide
Escape
Backspace
Type "-form-with-button"
Sleep 100ms
Show

Hide
Enter
Sleep 100ms
Show

Hide
Type "2"
Sleep 100ms
Show

Hide
Escape
Sleep 100ms
Show

Hide
Type "7"
Sleep 100ms
Show

Hide
Tab
Sleep 100ms
Show

Hide
Enter
Sleep 100ms
Show

Hide
Type "temporary pass00"
Enter
Sleep 100ms
Show

Sleep 100ms
