// Code generated by "idlimitsgenerator"; DO NOT EDIT.
package users

// SystemdSystemUidMax is the systemd-configured value for system_uid_max.
const SystemdSystemUidMax uint32 = 999

// SystemdSystemGidMax is the systemd-configured value for system_gid_max.
const SystemdSystemGidMax uint32 = 999

// SystemdDynamicUidMin is the systemd-configured value for dynamic_uid_min.
const SystemdDynamicUidMin uint32 = 61184

// SystemdDynamicUidMax is the systemd-configured value for dynamic_uid_max.
const SystemdDynamicUidMax uint32 = 65519

// SystemdContainerUidBaseMin is the systemd-configured value for container_uid_base_min.
const SystemdContainerUidBaseMin uint32 = 524288

// SystemdContainerUidBaseMax is the systemd-configured value for container_uid_base_max.
const SystemdContainerUidBaseMax uint32 = 1878982656
