// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package gdm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownType-0]
	_ = x[Hello-1]
	_ = x[Event-2]
	_ = x[EventAck-3]
	_ = x[Request-4]
	_ = x[Response-5]
	_ = x[Poll-6]
	_ = x[PollResponse-7]
	_ = x[lastDataType-8]
}

const _DataType_name = "UnknownTypeHelloEventEventAckRequestResponsePollPollResponselastDataType"

var _DataType_index = [...]uint8{0, 11, 16, 21, 29, 36, 44, 48, 60, 72}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
