// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package gdm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownEvent-0]
	_ = x[UserSelected-1]
	_ = x[BrokersReceived-2]
	_ = x[BrokerSelected-3]
	_ = x[AuthModesReceived-4]
	_ = x[AuthModeSelected-5]
	_ = x[ReselectAuthMode-6]
	_ = x[AuthEvent-7]
	_ = x[UILayoutReceived-8]
	_ = x[StartAuthentication-9]
	_ = x[IsAuthenticatedRequested-10]
	_ = x[StageChanged-11]
	_ = x[lastEventType-12]
}

const _EventType_name = "UnknownEventUserSelectedBrokersReceivedBrokerSelectedAuthModesReceivedAuthModeSelectedReselectAuthModeAuthEventUILayoutReceivedStartAuthenticationIsAuthenticatedRequestedStageChangedlastEventType"

var _EventType_index = [...]uint8{0, 12, 24, 39, 53, 70, 86, 102, 111, 127, 146, 170, 182, 195}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
