name: Main Documentation Checks

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/automatic-doc-checks.yml
      - .readthedocs.yaml
      - docs/**
  pull_request:
    paths:
      - .github/workflows/automatic-doc-checks.yml
      - .readthedocs.yaml
      - docs/**
  schedule:
    - cron:  '0 12 * * MON'
  # Manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: "./docs"
