name: Update translations and Rust packaging related files in main
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - debian/control
concurrency: auto-update

permissions:
  pull-requests: write
  contents: write

# Jobs in this action must not run concurrently, as they modify the repository.
# When adding more jobs, make sure to use the "needs:" attribute to make sure they run sequentially.
jobs:
  update-rust-packaging:
    name: Update packaging related Rust files
    runs-on: ubuntu-24.04 # ubuntu-latest-runner
    steps:
      - uses: actions/checkout@v4
        # with:
          # FIXME: US!
          # ref: main
      - name: Vendor the dependencies
        uses: kohlerdominik/docker-run-action@v2.0.0
        with:
          image: ubuntu:devel
          volumes: ${{ github.workspace }}:${{ github.workspace }}
          workdir: ${{ github.workspace }}
          shell: bash
          environment: |
            DEBIAN_FRONTEND=noninteractive
            CARGO_VENDOR_DIR=${{ github.workspace }}/vendor_rust
            CARGO_PATH=/usr/share/cargo/bin/cargo
          run: |
            echo "::group::Install dependencies"
            set -euo pipefail

            apt update -y
            apt install -y dh-cargo cargo-vendor-filterer
            echo "::endgroup::"

            set +x

            # FIXME:
            # apt install -y wget
            # wget https://launchpad.net/ubuntu/+source/dh-cargo/31ubuntu4/+build/30122553/+files/dh-cargo_31ubuntu4_all.deb
            # apt install -y ./dh-cargo_31ubuntu4_all.deb

            echo "::group::Vendor the dependencies"
            # export CARGO_VENDOR_DIR=${PWD}/vendor_rust
            # export CARGO_PATH=/usr/share/cargo/bin/cargo
            sh -x debian/vendor-rust.sh
            echo "::endgroup::"

            echo "::group::Update XS-Vendored-Sources-Rust"
            VENDORED_SOURCES=$(/usr/share/cargo/bin/dh-cargo-vendored-sources)
            OUTPUT=$(echo "$VENDORED_SOURCES" | grep ^XS-Vendored-Sources-Rust: || true)
            if [ -z "$OUTPUT" ]; then
              echo "XS-Vendored-Sources-Rust is up to date. No change is needed.";
              exit 0
            fi
            sed -i "s/^XS-Vendored-Sources-Rust:.*/$OUTPUT/" debian/control

            echo "modified=true" >> "${GITHUB_ENV}"
            echo "::endgroup::"

      # - name: Vendor the dependencies
      #   run: |
      #     cargo vendor vendor_rust/
      # - name: Update XS-Vendored-Sources-Rust
      #   shell: bash
      #   run: |
      #     set -eu

      #     export CARGO_VENDOR_DIR=vendor_rust/
      #     VENDORED_SOURCES=$(/usr/share/cargo/bin/dh-cargo-vendored-sources 2>&1 || true)
      #     OUTPUT=$(echo "$VENDORED_SOURCES" | grep ^XS-Vendored-Sources-Rust: || true)
      #     if [ -z "$OUTPUT" ]; then
      #       echo "XS-Vendored-Sources-Rust is up to date. No change is needed.";
      #       exit 0
      #     fi
      #     sed -i "s/^XS-Vendored-Sources-Rust:.*/$OUTPUT/" debian/control

      #     echo "modified=true" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto update packaging related Rust files
          title: Auto update packaging related Rust files
          labels: control, automated pr
          branch: auto-update-rust-packaging
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-rust-packaging:main
