name: Build debian packages

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

env:
  UBUNTU_VERSIONS: |
    ["noble", "devel"]

jobs:
  define-versions:
    name: Define build versions
    runs-on: ubuntu-latest
    outputs:
      ubuntu-versions: ${{ env.UBUNTU_VERSIONS }}
    steps:
      - run: 'true'

  build-deb-package:
    name: Build ubuntu package
    runs-on: ubuntu-latest
    needs: define-versions
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: ${{ fromJSON(needs.define-versions.outputs.ubuntu-versions) }}
    outputs:
      run-id: ${{ github.run_id }}
      pkg-src-changes: ${{ env.PKG_SOURCE_CHANGES }}

    steps:
      - name: Checkout authd code
        uses: actions/checkout@v4

      - name: Build debian packages and sources
        uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
        with:
          docker-image: ubuntu:${{ matrix.ubuntu-version }}
          extra-source-build-deps: |
            ca-certificates
            git
            libssl-dev
          extra-source-build-script: |
            cargo install --locked --root=/usr cargo-vendor-filterer
            command -v cargo-vendor-filterer

  run-autopkgtests:
    name: Run autopkgtests
    runs-on: ubuntu-latest
    needs:
      - define-versions
      - build-deb-package
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: ${{ fromJSON(needs.define-versions.outputs.ubuntu-versions) }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ needs.build-deb-package.outputs.run-id }}
        merge-multiple: true

    - name: Run autopkgtests
      uses: canonical/desktop-engineering/gh-actions/common/run-autopkgtest@main
      with:
        lxd-image: ubuntu:${{ matrix.ubuntu-version }}
        source-changes: ${{ needs.build-deb-package.outputs.pkg-src-changes }}
