name: Build debian packages

on:
  push:
    branches:
      - main
  pull_request:

env:
  UBUNTU_VERSIONS: '["latest", "devel"]'

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      ubuntu-versions: ${{ env.UBUNTU_VERSIONS }}
    steps:
      - run: 'true'

  build-deb-package:
    name: Build ubuntu package
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: ${{ fromJSON(needs.define-matrix.outputs.ubuntu-versions) }}
    outputs:
      run-id: ${{ github.run_id }}
      pkg-name: ${{ env.PKG_NAME }}
      pkg-version: ${{ env.PKG_VERSION }}
      # FIXME: use this when https://github.com/canonical/desktop-engineering/pull/58 is in
      # pkg-src-changes: ${{ env.PKG_SOURCE_CHANGES }}

    steps:
      - name: Checkout authd code
        uses: actions/checkout@v4

      - name: Build debian packages and sources
        uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
        with:
          docker-image: ubuntu:${{ matrix.ubuntu-version }}
          extra-source-build-deps: |
            ca-certificates
            git
            libssl-dev
          extra-source-build-script: |
            cargo install --locked --root=/usr cargo-vendor-filterer
            command -v cargo-vendor-filterer

  run-autopkgtests:
    name: Run autopkgtests
    runs-on: ubuntu-latest
    needs:
      - define-matrix
      - build-deb-package
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: ${{ fromJSON(needs.define-matrix.outputs.ubuntu-versions) }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ needs.build-deb-package.outputs.run-id }}
        merge-multiple: true

    - name: Run autopkgtests
      uses: 3v1n0/desktop-engineering/gh-actions/common/run-autopkgtest@run-autopkgtests
      # FIXME: ^^^
      with:
        lxd-image: ubuntu:${{ matrix.ubuntu-version }}
        source-changes: ${{ needs.build-deb-package.outputs.pkg-name }}_${{ needs.build-deb-package.outputs.pkg-version }}_source.changes
        # FIXME: Use this when https://github.com/canonical/desktop-engineering/pull/58 is in!
        # source-changes: ${{ needs.build-deb-package.outputs.pkg-src-changes }}
