name: Build debian packages

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

env:
  UBUNTU_VERSION: devel

jobs:
  build-deb-package:
    name: Build ubuntu package
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ github.run_id }}
      pkg-src-changes: ${{ env.PKG_SOURCE_CHANGES }}

    steps:
      - name: Checkout authd code
        uses: actions/checkout@v4

      - name: Build debian packages and sources
        uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
        with:
          docker-image: ubuntu:${{ env.UBUNTU_VERSION }}
          extra-source-build-deps: |
            ca-certificates
            git
            libssl-dev
          extra-source-build-script: |
            cargo install --locked --root=/usr cargo-vendor-filterer
            command -v cargo-vendor-filterer

  run-autopkgtests:
    name: Run autopkgtests
    needs: build-deb-package
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ needs.build-deb-package.outputs.run-id }}
        merge-multiple: true

    - name: Run autopkgtests
      uses: canonical/desktop-engineering/gh-actions/common/run-autopkgtest@main
      with:
        lxd-image: ubuntu:${{ env.UBUNTU_VERSION }}
        source-changes: ${{ needs.build-deb-package.outputs.pkg-src-changes }}
