name: Build debian packages

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - "*"
  pull_request:

env:
  DEBIAN_FRONTEND: noninteractive
  DEBCONF_NONINTERACTIVE_SEEN: true
  TERM: dumb

jobs:
  build-deb-package:
    name: Build ubuntu packages
    runs-on: ubuntu-latest

    # env:
    #   AS_USER: runuser -u builder --

    # container:
    #   image: ubuntu:devel

    steps:
    # - name: Prepare container
    #   run: |
    #     echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90aptyes
    #     apt update
    #     apt upgrade
    #     apt install git sudo
    #     git config --system --add safe.directory $PWD

    - name: Checkout authd code
      uses: actions/checkout@v4

    - name: Build debian packages and sources
      uses: canonical/desktop-engineering/gh-actions/common/build-debian@build-deb-lintian
      with:
        docker-image: ubuntu:devel

    # - name: Setup build user
    #   run: |
    #     adduser --disabled-password --gecos "" builder
    #     chown builder:builder . -R

    # - name: Build packages
    #   run: |
    #     export DEBEMAIL="$(git log -1 --format='%ae' HEAD)"
    #     export DEBFULLNAME="$(git log -1 --format='%an' HEAD)"
    #     $AS_USER dch --local "+git$(git rev-parse --short HEAD)" "CI: Autoamtic build"
    #     $AS_USER dpkg-buildpackage -b --jobs=$(getconf _NPROCESSORS_ONLN)
    #     mv -v ../*.*deb .
    #     ls -lht *.*deb

    # - name: Archiving built debs
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: debian-packages
    #     path: ./*.*deb
    #     if-no-files-found: error

    # - name: Install built debs
    #   run: |
    #     apt install --simulate ./*.deb

    # - name: Lint generated debs
    #   run: |
    #     apt install lintian
    #     lintian --pedantic --fail-on error ./*.deb

  # test-deb-package:
  #   name: Test ubuntu packages
  #   needs: build-deb-package
  #   runs-on: ubuntu-latest

  #   # env:
  #   #   AS_USER: runuser -u builder --

  #   container:
  #     image: ubuntu:devel
