name: Build debian packages

on:
  push:
    branches:
      - main
  pull_request:

env:
  UBUNTU_VERSION: devel

jobs:
  build-deb-package:
    name: Build ubuntu package
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ github.run_id }}
      pkg-name: ${{ env.PKG_NAME }}
      pkg-version: ${{ env.PKG_VERSION }}

    steps:
      - name: Checkout authd code
        uses: actions/checkout@v4

      - name: Build debian packages and sources
        uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
        with:
          docker-image: ubuntu:${{ env.UBUNTU_VERSION }}
          extra-source-build-deps: |
            ca-certificates
            git
            libssl-dev
          extra-source-build-script: |
            cargo install --locked --root=/usr cargo-vendor-filterer
            command -v cargo-vendor-filterer
