# By defaults, only bugs tagged with "jira" will be imported by this automation.

name: Sync GitHub issues to Jira
on: [issues, issue_comment]

env:
  UBUNTU_LATEST_RUNNER: ubuntu-24.04

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: ${UBUNTU_LATEST_RUNNER}
    steps:
      - uses: canonical/sync-issues-github-jira@v1
        with:
          # TODO: JIRA_WEBHOOK_URL should be stored as secret on the repository.
          # Ask your Jira project administrator for it.
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}
          component: 'Enterprise'
