[package]
name = "nss"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "nss_authd"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Allows to override the socket path used to connect to the grpc server, through the AUTHD_NSS_SOCKET env variable.
custom_socket = []
integration_tests = []

[dependencies]
libnss = "0.5.0"
lazy_static = "1.4.0"
libc = "0.2.150"
paste = "1.0.14"
tonic = "0.10.2"
prost = "0.12.3"
tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
log = "0.4.20"
simple_logger = {version = "4.3.0", features = ["stderr"]}
syslog = "6.1.0"
ctor = "0.2.5"

[build-dependencies]
tonic-build = "0.10.2"
cc = "1.0.84"
